version: '3'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app